changelog:
  exclude:
    messages: ["chore(release):*"]
  categories:
    - title: 🐛 Bug Fixes
      commit_types: ["fix"]
    - title: ✨ New Features
      commit_types: ["feat"]
    - title: 🔨 Refactor & Optimize
      commit_types: ["refactor", "perf"]
    - title: ⚙️ Chores & Maintenance
      commit_types: ["chore", "build", "ci"]
    - title: 📄 Documentation
      commit_types: ["docs"]